Middleware solution and new endpoints
volcanic-uk/Authenticator-node-module pull request #53
Opened 2020-08-18 08:26 UTC by nisalikularatne

2020-08-18 08:36 UTC, daniakabani commented on src/authenticator/v1/middleware/authorization.js
> +let t;
what's t?

2020-08-19 03:12 UTC, daniakabani approved these changes
![approved](https://user-images.githubusercontent.com/27546352/90587827-dfc5f980-e20c-11ea-918e-dabc225af6a5.jpg)

2020-08-19 03:23 UTC, Ali-Dalal requested changes
some minor changes are required. after, the PR ready to go

2020-08-19 03:23 UTC, Ali-Dalal commented on src/authenticator/v1/middleware/authorization.js
> +};
don't define global singleton token, it is very bad practice in a multithreaded environment.

We've done something similar in Aggregator project, check the code there, please.

2020-08-19 03:23 UTC, Ali-Dalal commented on test/helpers/index.js
> +        console.log('check here');
console.log?

2020-08-19 08:43 UTC, Ali-Dalal requested changes
1 more fix

2020-08-19 08:43 UTC, Ali-Dalal commented on src/authenticator/v1/middleware/authorization.js
> +        }
can we replace this `if` with a logical operation?
```js
await authorization.authorize({
            serviceName: serviceName || serviceNameMain,
            permissionName,
            resourceType,
            resourceID,
            datasetID
        });
```

2020-08-19 09:09 UTC, Ali-Dalal approved these changes
✨

2020-08-19 09:30 UTC, merged